Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -36,16 +36,33 @@ jobs:
           output: both
           thresholds: '20 60'
 
-      - name: Print code-coverage-results.md
-        run: cat code-coverage-results.md
-
       - name: Extract Coverage Percentage from Report
         id: extract_coverage
         run: |
           COVERAGE_PERCENTAGE=$(grep "EcoState" code-coverage-results.md | sed 's/^.*EcoState | \([0-9]*%\) | .*$/\1/' | cut -d'%' -f1)
-      
           echo "COVERAGE_PERCENTAGE=$COVERAGE_PERCENTAGE" >> $GITHUB_ENV
           echo "::set-output name=coverage_percentage::$COVERAGE_PERCENTAGE"
+
+      - name: Determine Badge Color
+        id: determine_color
+        run: |
+          COVERAGE_PERCENTAGE="${{ env.COVERAGE_PERCENTAGE }}"
+          if [[ -z "$COVERAGE_PERCENTAGE" ]]; then
+            COVERAGE_COLOR="red"
+            echo "COVERAGE_COLOR=$COVERAGE_COLOR" >> $GITHUB_ENV
+            exit 1  # Exit with error so action will fail
+          fi
+
+          COVERAGE_INT=$(echo "$COVERAGE_PERCENTAGE" | tr -d ' ') # Remove spaces
+          if [[ "$COVERAGE_INT" -lt 20 ]]; then
+            COVERAGE_COLOR="red"
+          elif [[ "$COVERAGE_INT" -gt 60 ]]; then
+            COVERAGE_COLOR="green"
+          else
+            COVERAGE_COLOR="yellow"
+          fi
+          echo "COVERAGE_COLOR=$COVERAGE_COLOR" >> $GITHUB_ENV
+          echo "::set-output name=coverage_color::$COVERAGE_COLOR"
 
 
       - name: Create Awesome Badge
@@ -56,4 +73,4 @@ jobs:
           filename: test.json
           label: Coverage
           message: ${{ env.COVERAGE_PERCENTAGE }}%
-          color: yellow
+          color: ${{ env.COVERAGE_COLOR }}%
