Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -23,37 +23,32 @@ jobs:
       - name: Test with the dotnet CLI
         run: dotnet test EcoState.Test/EcoState.Test.csproj --collect:"XPlat Code Coverage" --results-directory ./coverage
 
-      - name: Create Coverage Directory
-        run: mkdir -p coverage  # Создаем каталог coverage
+      - name: Install xmllint
+        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
 
-      - name: Code Coverage Report
-        id: coverage-report
-        uses: irongut/CodeCoverageSummary@v1.3.0
-        with:
-          filename: coverage/**/coverage.cobertura.xml
-          badge: true
-          fail_below_min: true
-          format: markdown
-          hide_branch_rate: false
-          hide_complexity: true
-          indicators: true
-          report_only: true # Only output the badge URL
-          output: console # Make sure the URL is printed to the console
-          thresholds: '20 60'
-
-      - name: Extract Badge URL
-        id: extract-badge-url
+      - name: Extract Coverage Percentage from XML
+        id: extract_coverage
         run: |
-          BADGE_URL=$(echo "${{ steps.coverage-report.outputs.report }}" | grep -oP 'https:\/\/img\.shields\.io\/badge\/Code%20Coverage-\d+%25-[a-z]+(\?style=flat)?')
-          echo "BADGE_URL=$BADGE_URL" >> $GITHUB_ENV
+          COVERAGE_XML=$(find ./coverage -name "coverage.cobertura.xml")
+          if [ -z "$COVERAGE_XML" ]; then
+            echo "Error: coverage.cobertura.xml not found"
+            exit 1
+          fi
+
+          TOTAL_LINES=$(xmllint --xpath "sum(//line[@condition-coverage='100%']/@count + //line[not(@condition-coverage)]/@count)" "$COVERAGE_XML")
+          COVERED_LINES=$(xmllint --xpath "sum(//line[@condition-coverage])" "$COVERAGE_XML")
+          # Calculate percentage
+          COVERAGE_PERCENTAGE=$(( $(echo "scale=2; $COVERED_LINES / $TOTAL_LINES * 100" | bc) + 0.5 ))
+          echo "COVERAGE_PERCENTAGE=$COVERAGE_PERCENTAGE" >> $GITHUB_ENV
+
         shell: bash
 
-      - name: Update Gist with Badge URL
+      - name: Create Awesome Badge
         uses: schneegans/dynamic-badges-action@v1.7.0
         with:
           auth: ${{ secrets.GIST_SECRET }}
           gistID: 4a7a6924fbbad82e9ee021b9e5205127
           filename: test.json
-          label: Coverage Badge
-          message: ${{ env.BADGE_URL }}
-          color: green # You can choose any color here, it won't affect the badge's appearance
+          label: Coverage
+          message: ${{ env.COVERAGE_PERCENTAGE }}%
+          color: yellow
